version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: hacker_wackers
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    working_dir: /backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/hacker_wackers
      - JWT_SECRET=your_jwt_secret
      - PORT=8080
    command: ["npm", "start"]
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"

volumes:
  mongo_data:
